name: CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify:
    uses: ./.github/workflows/notify-slack.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  test:
    needs:
      - notify
    uses: ./.github/workflows/test-webapp.yml
    with:
      build-enabled: true
      tests-enabled: true

  deploy-dev-fusion:
    if: ${{ needs.notify.outputs.branch-name == 'develop' }}
    needs:
      - notify
      - test
    uses: ./.github/workflows/deploy-amplify.yml
    with:
      aws-region: eu-central-1
      app-name: ipor-dev-fusion-website
      branch: develop
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-dev-ipor:
    if: ${{ needs.notify.outputs.branch-name == 'develop' }}
    needs:
      - notify
      - test
    uses: ./.github/workflows/deploy-amplify.yml
    with:
      aws-region: eu-central-1
      app-name: ipor-dev-main-website
      branch: develop
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  report:
    if: ${{ always() }}
    needs:
      - notify
      - test
      - deploy-dev-fusion
      - deploy-dev-ipor
    uses: ./.github/workflows/report-slack.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    with:
      success: ${{ (needs.notify.outputs.branch-name == 'develop' && needs.test.result == 'success' && needs.deploy-dev-fusion.result == 'success' && needs.deploy-dev-ipor.result == 'success') || (needs.notify.outputs.branch-name == 'main' && needs.test.result == 'success') }}
      slack-status-msg-id: ${{ needs.notify.outputs.slack-status-msg-id }}
